/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'article',
    path: '/article',
    component: 'layout.base$view.article',
    meta: {
      title: 'article',
      i18nKey: 'route.article',
      icon: 'mdi:file-text'
    }
  },
  {
    name: 'blogger',
    path: '/blogger',
    component: 'layout.base$view.blogger',
    meta: {
      title: 'blogger',
      i18nKey: 'route.blogger',
      icon: 'mdi:account'
    }
  },
  {
    name: 'category',
    path: '/category',
    component: 'layout.base$view.category',
    meta: {
      title: 'category',
      i18nKey: 'route.category',
      icon: 'mdi:folder'
    }
  },
  {
    name: 'comment',
    path: '/comment',
    component: 'layout.base$view.comment',
    meta: {
      title: 'comment',
      i18nKey: 'route.comment',
      icon: 'mdi:comment-text-outline'
    }
  },
  {
    name: 'friend-link',
    path: '/friend-link',
    component: 'layout.base$view.friend-link',
    meta: {
      title: 'friend-link',
      i18nKey: 'route.friend-link',
      icon: 'mdi:link'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'portfolio',
    path: '/portfolio',
    component: 'layout.base$view.portfolio',
    meta: {
      title: 'portfolio',
      i18nKey: 'route.portfolio',
      icon: 'mdi:briefcase'
    }
  },
  {
    name: 'tag',
    path: '/tag',
    component: 'layout.base$view.tag',
    meta: {
      title: 'tag',
      i18nKey: 'route.tag',
      icon: 'mdi:tag'
    }
  }
];
